#!/bin/bash

#Copy this script to .git/hooks/pre-commit to enable automatic version incrementing

SCRIPTDIR="$( cd "$(dirname $0)" && pwd )"

cd $SCRIPTDIR/../..
BRANCH=$(git branch | grep "\*")
[[ "$BRANCH" == "* master" || "$BRANCH" == "* testing" ]] && exit 0
REVISION_FILE=$SCRIPTDIR/../../revision.txt
REVISION=$(cat $REVISION_FILE)
REVISION=$(($REVISION + 1))
echo $REVISION > $REVISION_FILE
git add revision.txt
